name: Trabalhos de Grafos
description: Trabalhos da disciplina de Teoria dos Grafos, ministrada pelo professor Alexandre Levada na Universidade Federal de São Carlos (UFSCar). São Carlos, 2017.
theme: jekyll-theme-slate